### ISSUE TITLE
无法安装产品密钥

### ISSUE THREAD

**Issue by auauauto** [TGSAN/CMWTAT_Digital_Edition#11]
无法安装密钥，可能没有选择或输入正确的版本：（代码：-2

**Comment by TGSAN** [comment]
请附带原始Windows版本和目标Windows版本

**Comment by leonvogle** [comment]
> 无法安装密钥，可能没有选择或输入正确的版本：（代码：-2

这种情况都是选择错了版本，可以试试教育版或者家庭版的激活方式

**Comment by HuoYingCunCunZhang** [comment]
我的情况跟作者提供的方式类似，成功的激活了，感谢作者。

**Comment by zhaodon** [comment]
win11专业版 N 无法切换到专业版，只能切换到企业版，谁还有其他办法？  提示：无法安装密钥，可能没有选择或输入正确的版本：（代码：-2

**Comment by TGSAN** [comment]
> win11专业版 N 无法切换到专业版，只能切换到企业版 N，谁还有其他办法？ 提示：无法安装密钥，可能没有选择或输入正确的版本：（代码：-2

N版不能和普通版本互转，因为系统文件不一样

**Comment by TheRainTime** [comment]
win10家庭版 21H1 升级不了，我试过大部分的激活方式，均显示  无法安装密钥，可能没有选择或输入正确的版本：（代码：-2

**Comment by TGSAN** [comment]
> win10家庭版 21H1 升级不了，我试过大部分的激活方式，均显示 无法安装密钥，可能没有选择或输入正确的版本：（代码：-2

指路->[https://github.com/TGSAN/CMWTAT_Digital_Edition#%E5%9C%A8%E4%B8%8D%E5%90%8C%E7%89%88%E6%9C%AC-windows-10-%E4%B9%8B%E9%97%B4%E8%BD%AC%E6%8D%A2](https://github.com/TGSAN/CMWTAT_Digital_Edition#%E5%9C%A8%E4%B8%8D%E5%90%8C%E7%89%88%E6%9C%AC-windows-10-%E4%B9%8B%E9%97%B4%E8%BD%AC%E6%8D%A2)

**Comment by Kenshin-GR** [comment]
-1 无法卸载密匙  sppcext.dll没有被指定在 Windows 上运行，或者它包含错误。请尝试使用原始安
装介质重新安装程序，或联系你的系统管理员或软件供应商以获取支持。错误状态Oxc0000428 
试过将别人电脑上的sppcext.dll复制到 本地并安装，但不起效果，有大佬知道怎么处理吗，谢谢

**Comment by TGSAN** [comment]
> -1 无法卸载密匙 sppcext.dll没有被指定在 Windows 上运行，或者它包含错误。请尝试使用原始安
> 装介质重新安装程序，或联系你的系统管理员或软件供应商以获取支持。错误状态Oxc0000428
> 试过将别人电脑上的sppcext.dll复制到 本地并安装，但不起效果，有大佬知道怎么处理吗，谢谢

系统损坏了，这个dll是系统授权服务的一个组件。这个组件没了很大概率系统里其它关键组件也有损坏，如果不是自己删掉的，可能系统本身是被过度精简坏了的魔改版。

**Comment by Kenshin-GR** [comment]
已重装系统了，谢谢，请问以后可以支持家庭版可以升专业版吗

**Comment by TGSAN** [comment]
> 已重装系统了，谢谢，请问以后可以支持家庭版可以升专业版吗

以后会加的，不过应该只会有家庭版升企业版，不过可以升级之后再改成专业版或者其他版本

**Comment by 2well-debug** [comment]
哎，不行欸
