### ISSUE TITLE
您好请问怎么取消激活？

### ISSUE THREAD

**Issue by WystanW** [TGSAN/CMWTAT_Digital_Edition#13]
请问，用了这款工具之后，重新全盘格式化安装windows发现还是激活状态，这款工具是直接将主板修改了吗？有没有办法取消，主要是装双系统时发现bios无法识别u盘了不知道和这款工具有没有关系

**Comment by TGSAN** [comment]
怎么可能修改主板

**Comment by TGSAN** [comment]
#12
