### ISSUE TITLE
激活时在“正在获取免费更新许可”卡住，并提示“执行超时，可能没有选择正确或输入的版本。代码：-3”

### ISSUE THREAD

**Issue by YagamiMirai** [TGSAN/CMWTAT_Digital_Edition#15]
之前版本为企业版，转换为专业版后版本转换成功但激活时出现此问题。

**Comment by TGSAN** [comment]
windows update服务和clipsvc服务必须处于运行状态才可以用，另外Windows 10的正版软件授权服务也要保持运行。
