### ISSUE TITLE
无法切换版本

### ISSUE THREAD

**Issue by zhengjie74** [TGSAN/CMWTAT_Digital_Edition#19]
无法安装密钥，可能没有选择或输入正确的版本：（代码：-2）
Windows版本 
版本	Windows 10 家庭中文版
版本号	20H2
操作系统版本	19042.685
体验	Windows Feature Experience Pack 120.2212.551.0
想切成专业版失败

**Comment by TGSAN** [comment]
请阅读：[https://github.com/TGSAN/CMWTAT_Digital_Edition#%E5%9C%A8%E4%B8%8D%E5%90%8C%E7%89%88%E6%9C%AC-windows-10-%E4%B9%8B%E9%97%B4%E8%BD%AC%E6%8D%A2](url)

**Comment by dyxang** [comment]
> 请阅读：[https://github.com/TGSAN/CMWTAT_Digital_Edition#%E5%9C%A8%E4%B8%8D%E5%90%8C%E7%89%88%E6%9C%AC-windows-10-%E4%B9%8B%E9%97%B4%E8%BD%AC%E6%8D%A2](url)

点进去什么都没有

**Comment by TGSAN** [comment]
> > 请阅读：[https://github.com/TGSAN/CMWTAT_Digital_Edition#%E5%9C%A8%E4%B8%8D%E5%90%8C%E7%89%88%E6%9C%AC-windows-10-%E4%B9%8B%E9%97%B4%E8%BD%AC%E6%8D%A2](url)
> 
> 点进去什么都没有

markdown 指向链接和链接的说明文字写反了，已更新
