### ISSUE TITLE
被报毒CMWTAT_Digital_Release_2_5_0_0.exe

### ISSUE THREAD

**Issue by shui0855** [TGSAN/CMWTAT_Digital_Edition#2]
经测试在win7x64下被360报毒：

类型:木马-HEUR/QVM03.0.4AA3.Malware.Gen
描述:木马是一种伪装成正常文件的恶意软件，会盗取您的帐号、密码等隐私资料。
扫描引擎:云特征引擎
文件路径:D:\CMWTAT_Digital_Release_2_5_0_0.exe
文件大小:10.06M (10,549,760 字节)
文件版本:2.5.0.0
文件描述:CMWTAT Digital Edition V2
文件指纹（MD5）:36b3330b471eb5a257a93e45cc3b37f7
处理建议:隔离文件

**Comment by TGSAN** [comment]
QVM报毒结果其实并不可信，因为这是360自家的通过机器学习（人工智能）进行判断的引擎（和Windows Defender的云查杀原理一样），众所周知这种方法目前准确率很低。

另注VirusTotal中扫描结果中只有Microsoft（Windows Defender）、Rising（瑞星）、和Sophos AV报毒，在结果中Qihoo360没有报毒。

其实怀疑是因为可以执行外部程序（cmd.exe）的原因导致的报毒。

附VirusTotal各杀毒软件报毒情况（结果未来可能发生变化）：

[https://www.virustotal.com/#/file/1eda6f60b4936030006fb2e062a5919ce1662c04b0b8191c96e8f0ccc8825870/detection](url)

附VirusTotal扫描结果：

>
> SHA-256 - 1eda6f60b4936030006fb2e062a5919ce1662c04b0b8191c96e8f0ccc8825870
> CMWTAT_Digital_Release_2_5_0_0.exe
> 10.06 MB
> 2019-01-03 04:42:33 UTC
> 
> Microsoft
> - [ ] PUA:Win32/Presenoker
> 
> Rising
> - [ ] PUA.Presenoker!8.F608 (CLOUD)
> 
> Sophos AV
> - [ ] Generic PUA KK (PUA)
> 
> Qihoo-360
> - [x] Clean
> 
> Others
> - [x] Clean
> 

File Hash 文件哈希：
```
PS C:\Users\TGSAN> CertUtil -hashfile C:\Users\TGSAN\Desktop\CMWTAT_Digital_Release_2_5_0_0.exe SHA256
SHA256 的 C:\Users\TGSAN\Desktop\CMWTAT_Digital_Release_2_5_0_0.exe 哈希:
1eda6f60b4936030006fb2e062a5919ce1662c04b0b8191c96e8f0ccc8825870
CertUtil: -hashfile 命令成功完成。
PS C:\Users\TGSAN> CertUtil -hashfile C:\Users\TGSAN\Desktop\CMWTAT_Digital_Release_2_5_0_0.exe MD5
MD5 的 C:\Users\TGSAN\Desktop\CMWTAT_Digital_Release_2_5_0_0.exe 哈希:
36b3330b471eb5a257a93e45cc3b37f7
CertUtil: -hashfile 命令成功完成。
```

解决办法：

1. 通过杀毒软件论坛反馈误报。

2. 更换杀毒软件。

3. 自行编译（资源文件中分别可从官方安装源里找到、slc文件源码附下方，下载后编译即可）。

[https://github.com/vyvojar/slshim/archive/v11.tar.gz](url)
