### ISSUE TITLE
提示无法卸载旧密钥

### ISSUE THREAD

**Issue by jasonzhou037** [TGSAN/CMWTAT_Digital_Edition#20]
![image](https://user-images.githubusercontent.com/38002363/108618507-e18da580-7459-11eb-9cc3-373aa16e182d.png)

**Comment by Darcy-Zhang** [comment]
是不是之前用其他方式破解系统未成功？请上网搜索如何卸载已有密钥，清除原来所有密钥后再尝试破解（我的经验）。
另外，提issue请附上足够的信息，同时应尽量避免错别字，具体内容请上网搜索提问的艺术。

**Comment by jasonzhou037** [comment]
> 是不是之前用其他方式破解系统未成功？请上网搜索如何卸载已有密钥，清除原来所有密钥后再尝试破解（我的经验）。
> 另外，提issue请附上足够的信息，同时应尽量避免错别字，具体内容请上网搜索提问的艺术。

嗯嗯嗯，我试试啊

**Comment by jasonzhou037** [comment]
> 是不是之前用其他方式破解系统未成功？请上网搜索如何卸载已有密钥，清除原来所有密钥后再尝试破解（我的经验）。
> 另外，提issue请附上足够的信息，同时应尽量避免错别字，具体内容请上网搜索提问的艺术。

我搞好了。谢谢你的思路
步骤：
1.上网搜索如何卸载已有密钥，清除原来所有密钥后再尝试破解
2.管理员运行注册软件，破解。

**Comment by jasonzhou037** [comment]
步骤：
1.上网搜索如何卸载已有密钥，清除原来所有密钥后再尝试破解
2.管理员运行注册软件，破解。
