### ISSUE TITLE
请支持win11

### ISSUE THREAD

**Issue by peterwillcn** [TGSAN/CMWTAT_Digital_Edition#24]
请支持win11

**Comment by TGSAN** [comment]
支持的

**Comment by SnowyLake** [comment]
事实上，Win11可以被Win10的秘钥直接激活。

**Comment by TGSAN** [comment]
> 事实上，Win11可以被Win10的秘钥直接激活。

是的，但鉴于目前Win11还处于测试阶段，不敢确定最终是否会更改SKU对应的密钥。

**Comment by ccicnce113424** [comment]
![image](https://user-images.githubusercontent.com/30774232/124945480-c1ddcf00-e040-11eb-8f11-8e74b5e026e6.png)
shi'ce'ke'xin实测可行

**Comment by lc6464** [comment]
目前来说支持的，因为 Windows 11 激活相关的底层原理并没有被改变。

**Comment by lrgcx** [comment]
我的21h1自动和手动都不能激活，虚拟机安装。

**Comment by lc6464** [comment]
> 我的21h1自动和手动都不能激活，虚拟机安装。

建议你新开一个议题，并附上相关信息。

**Comment by shnke666666** [comment]
真的支持Win11么？

**Comment by fe1w0** [comment]
![image](https://user-images.githubusercontent.com/50180586/143260486-d363a882-fdfa-4640-90ef-1908acc214ba.png)
支持win11 arm64版(parallels desktop 17.1 m1版)

**Comment by TGSAN** [comment]
> ![image](https://user-images.githubusercontent.com/50180586/143260486-d363a882-fdfa-4640-90ef-1908acc214ba.png) 支持win11 arm64版(parallels desktop 17.1 m1版)

计划下版本支持，ARM64 支持相关问题可以在此讨论 #30

**Comment by zhouxx2018** [comment]
> ![图片](https://user-images.githubusercontent.com/50180586/143260486-d363a882-fdfa-4640-90ef-1908acc214ba.png) 支持win11 arm64版(并行桌面17.1 m1版)

请问有遇到一直正在获取免费升级许可的情况吗？我也是m1的pd虚拟机，一直卡在这儿，无论是否挂梯子都这样。

**Comment by qing-root** [comment]
> > ![图片](https://user-images.githubusercontent.com/50180586/143260486-d363a882-fdfa-4640-90ef-1908acc214ba.png) 支持win11 arm64版(并行桌面17.1 m1版)
> 
> 请问有遇到一直正在获取免费升级许可的情况吗？我也是m1的pd虚拟机，一直卡在这儿，无论是否挂梯子都这样。

我也是 一只卡着 请问这个解决了吗

**Comment by zhouxx2018** [comment]
> 

一直等，就可以了。

**Comment by zhouxx2018** [comment]
@qing-root 我是一直挂在后台等待，他自己就好了。

> > > ![图片](https://user-images.githubusercontent.com/50180586/143260486-d363a882-fdfa-4640-90ef-1908acc214ba.png) 支持win11 arm64版(并行桌面17.1 m1版)
> > 
> > 
> > 请问有遇到一直正在获取免费升级许可的情况吗？我也是m1的pd虚拟机，一直卡在这儿，无论是否挂梯子都这样。
> 
> 我也是 一只卡着 请问这个解决了吗

**Comment by qing-root** [comment]
> @qing-root 我是一直挂在后台等待，他自己就好了。
> 
> > > > ![图片](https://user-images.githubusercontent.com/50180586/143260486-d363a882-fdfa-4640-90ef-1908acc214ba.png) 支持win11 arm64版(并行桌面17.1 m1版)
> > > 
> > > 
> > > 请问有遇到一直正在获取免费升级许可的情况吗？我也是m1的pd虚拟机，一直卡在这儿，无论是否挂梯子都这样。
> > 
> > 
> > 我也是 一只卡着 请问这个解决了吗

嗯嗯 激活啦
