### ISSUE TITLE
无法激活LTSC2021，望修复

### ISSUE THREAD

**Issue by Road-To-Gensokyo** [TGSAN/CMWTAT_Digital_Edition#29]
自动模式下显示只有实验性选项，并且无法激活成功，但LTSC2021实测是可以用KMS38激活的

**Comment by TGSAN** [comment]
目前有计划发布新版工具来进行LTS的数字激活，在此之前只能支持长期KMS激活。目前微软还没有在[文档](https://docs.microsoft.com/en-us/windows-server/get-started/kms-client-activation-keys)中放出KMS密钥（新版工具将会支持直接在本机获取激活密钥，而不需要等微软放出），如果有KMS密钥可以告知，有了KMS密钥后旧版工具可以不更新直接支持长期KMS激活。

**Comment by Road-To-Gensokyo** [comment]
我使用ltsc2019的kms密钥能够成功激活ltsc2021

**Comment by TGSAN** [comment]
已添加LTSC2021支持，待验证

**Comment by Road-To-Gensokyo** [comment]
已测试，可以成功激活kms38
