### ISSUE TITLE
你好，想尝试自己编译试试，但是好像缺少文件失败

### ISSUE THREAD

**Issue by iddddg** [TGSAN/CMWTAT_Digital_Edition#32]
翻阅历史issues，曾经给过一个链接，但是已经DMCA 。现在还能自己编译嘛？

**Comment by TGSAN** [comment]
这里有fork的备份[https://github.com/TGSAN/slshim](https://github.com/TGSAN/slshim)

**Comment by iddddg** [comment]
好的我试试。谢谢大佬
