### ISSUE TITLE
Cannot connect to Microsoft Activation Server

### ISSUE THREAD

**Issue by ruixing76** [TGSAN/CMWTAT_Digital_Edition#34]
Education->Profession版本间转换成功，但是在激活的时候出现 "However, it seems that Windows cannot connect to the Microsoft Activation Server."，一直无法激活，是不是现在无法激活了？

**Comment by TGSAN** [comment]
检查一下是不是连不上微软的激活服务器，或者看看有没有禁用掉Windows Update服务（wusvc）或者微软正版软件保护服务（clipsvc）。Get Outlook for Android
