### ISSUE TITLE
在”正在获取免费升级许可“卡住

### ISSUE THREAD

**Issue by NalCol** [TGSAN/CMWTAT_Digital_Edition#37]
系统：Windows 11 Pro On ARM 22000.778
硬件：小米8
网络：电信，测试时通畅

自动模式激活 在”正在获取免费升级许可“卡住。
跟ARM64架构有没有关系？
（注：测试另外一款W10 Digital Activation Program也是卡很久，不知道是不是架构问题。）

**Comment by TGSAN** [comment]
有关 ARM64 支持可以在此讨论 #30 ，这个 issue 里面也有一部分讨论 #24

**Comment by dahuigeniu** [comment]
good good
