### ISSUE TITLE
win10 专业工作站激活失败

### ISSUE THREAD

**Issue by kai2ou** [TGSAN/CMWTAT_Digital_Edition#44]
![image](https://user-images.githubusercontent.com/39549646/190590586-34c805e1-4088-43ad-942e-21f98aaa567c.png)

**Comment by TGSAN** [comment]
麻烦提供一下以下信息：
 - CPU 架构: [x86/x64/ARM64]
 - Windows 版本: [如：Windows 10 10.0.10240.0]
 - 原始版本: [如：家庭版/专业版/教育版 etc.]
 - 目标版本: [如：家庭版/专业版/教育版 etc.]
 - 软件版本号: [如：2.6.2.0]

**Comment by kai2ou** [comment]
- CPU 架构: x86（注：i5 10500，不知道对不对）
- Windows 版本: 版本20H2（OS内部版本19042.928）
- 原始版本: Windows10专业工作站版
- 目标版本: Windows10专业工作站版
- 软件版本号: V2.6.2.0
谢谢！

**Comment by kai2ou** [comment]
激活成功了，之前激活失败可能是因为关闭了windows update

**Comment by TGSAN** [comment]
> 激活成功了，之前激活失败可能是因为关闭了windows update

windows update服务关闭的话确实不能激活
