### ISSUE TITLE
提示无法定位程序输入点_CxxFrameHandler4于动态链接库。。。。ClipUp.exe上

### ISSUE THREAD

**Issue by jszsj** [TGSAN/CMWTAT_Digital_Edition#45]
**PC Information (please complete the following information):**
 - CPU Arch:x64
 - Windows Version: Windows 10 22H1
 - Original SKU: Pro
 - Target SKU: Pro/
 - Version 2.6.2.0

**Comment by TGSAN** [comment]
看上去是系统的运行环境有损坏，尝试在任务栏中点击搜索按钮，输入 `cmd` 选择 `以管理员身份运行`  
输入 `sfc /scannow` 然后按回车  
重启电脑后尝试是否可以正常运行，如果仍然报错，再次使用管理员身份运行cmd然后依次执行以下命令：  
```
dism.exe /online /cleanup-image /startcomponentcleanup
dism.exe /online /cleanup-image /scanhealth
dism.exe /online /cleanup-image /restorehealth
```
然后重启电脑后尝试，如果依然不能运行。可以尝试在 [https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist) 中下载并安装 `Visual Studio 2015, 2017, 2019, and 2022` C++ 运行库。

**Comment by Lancercmd** [comment]
> 看上去是系统的运行环境有损坏，尝试在任务栏中点击搜索按钮，输入 `cmd` 选择 `以管理员身份运行` 输入 `sfc /scannow` 然后按回车 重启电脑后尝试是否可以正常运行，如果仍然报错，再次使用管理员身份运行cmd然后依次执行以下命令：
> 
> ```
> dism.exe /online /cleanup-image /startcomponentcleanup
> dism.exe /online /cleanup-image /scanhealth
> dism.exe /online /cleanup-image /restorehealth
> ```
> 
> 然后重启电脑后尝试，如果依然不能运行。可以尝试在 https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist 中下载并安装 `Visual Studio 2015, 2017, 2019, and 2022` C++ 运行库。

为虚拟机使用 MediaCreationTool21H2 镜像全新安装 Windows 10 Pro 21H2 19044.1288 后同样遇到了这个问题
在 `sfc /scannow` 后也没能略过这个错误。

但使用 `Release 2.5.0.0` 便可正常完成激活。

**Comment by TGSAN** [comment]
我下次找个时间装个虚拟机试一下，之前测试是测的只有几个边缘版本（10240 x64 x86，22622 x64 arm64）

**Comment by Diadormu** [comment]
>版本	Windows 10 专业工作站版
>版本号	22H2
>安装日期	‎2022/‎10/‎21
>操作系统内部版本	19045.2130
>体验	Windows Feature Experience Pack 120.2212.4180.0

一样的报错，使用**Release 2.5.0.0**可以正常激活

**Comment by TGSAN** [comment]
更新了 v2.6.3 版本，修复了报错的问题

**Comment by lindexi** [comment]
_CxxFrameHandler4 是带在 c:\Windows\System32\ucrtbase.dll 里面的。 ucrt 是微软提供的 C 通用运行时。原本来说这个是不应该有 API 变更的，但是在 2019 12月时，微软决定添加了“更安全”的 _CxxFrameHandler4 方法，这就导致了如果更新了构建 SDK 动态依赖了 ucrt 库构建出来的应用，将会有此依赖。然而 c:\Windows\System32\ucrtbase.dll 是靠系统更新分发的，这就意味着在很多久系统，如 15061 等版本上，将找不到此方法，进而出现此异常

正好我遇到了 10.0.26100.2454 版本的 d3dcompiler_47.dll 有此问题，搜到了这个帖子，特来回复。感谢大佬们帮忙踩坑
