### ISSUE TITLE
有时候会失效，又得重新激活

### ISSUE THREAD

**Issue by CoreJK** [TGSAN/CMWTAT_Digital_Edition#5]
感谢大佬的激活工具，使用很方便。
但最近更新了系统后，出现了激活失效的问题。
需要再次重新激活。
![系统版本](https://user-images.githubusercontent.com/39509609/63415075-b888f080-c42f-11e9-8f62-b73f6cbd3814.png)

**Comment by qq626928256** [comment]
不知道你是否是在我的网站看到的，不过我之前使用云萌激活从未出现过这种情况，不过既然是免费激活，就再激活一次吧



------------------ 原始邮件 ------------------
发件人: "秋冥虫吟"<notifications@github.com>;
发送时间: 2019年8月21日(星期三) 下午4:23
收件人: "TGSAN/CMWTAT_Digital_Edition"<CMWTAT_Digital_Edition@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [TGSAN/CMWTAT_Digital_Edition] 有时候会失效，又得重新激活 (#5)




感谢大佬的激活工具，使用很方便。
 但最近更新了系统后，出现了激活失效的问题。
 需要再次重新激活。

**Comment by TGSAN** [comment]
一般激活失效都是因为连不上微软服务器导致的，不需要重新使用工具激活，在设置-更新和安全-激活里选择疑难解答可以手动重新请求微软服务器拉取授权。如果不是因为连不上服务器导致的失效（比如硬件ID变更）疑难解答会直接告诉你这台电脑没有许可证（或者询问是否更换硬件进行授权迁移）。重新激活的话也只是手动请求一遍微软服务器（如果重新使用激活工具你会发现虽然工具还在显示激活中，但是实际上系统状态已经变为激活）

**Comment by CoreJK** [comment]
谢谢回复，最近没有出现该状况了。
应该是网络原因。
