### ISSUE TITLE
Error 0x800705B4 Windows10家庭版 激活失败

### ISSUE THREAD

**Issue by NasdaqGodzilla** [TGSAN/CMWTAT_Digital_Edition#52]
**Describe the bug**
Activating windows failed: Huawei MateBook B5 家庭版 windows10；使用CMWTAT切换到Windows10专业版并激活。

切换专业版成功但是激活失败：
![image](https://user-images.githubusercontent.com/26323326/197914221-f56dfbe6-fb1a-4096-a3c7-b21a4a65b736.png)

**To Reproduce**
1. 切换到Windows10专业版
2. 激活
3. 失败

![image](https://user-images.githubusercontent.com/26323326/197914576-60b57ea0-2342-4884-b661-a5d12c958be0.png)

**Comment by TGSAN** [comment]
可以检查一下是否禁用了Windows Update

**Comment by NasdaqGodzilla** [comment]
> 可以检查一下是否禁用了Windows Update

It works! Thank you.
