### ISSUE TITLE
激活成功，但是无法连接微软激活服务器

### ISSUE THREAD

**Issue by RinChanNOWWW** [TGSAN/CMWTAT_Digital_Edition#53]
Windows Update 和 ClipSVC 服务已打开。

原始版本：
Windows 11 家庭版 22H2

操作：升级完整版 -> 激活专业版

![image](https://user-images.githubusercontent.com/33975039/200106660-dadea6b7-c82f-41cf-9f28-37b07adae9a7.png)

![image](https://user-images.githubusercontent.com/33975039/200106295-1b511d71-f453-4876-a58a-922e16a791b4.png)

疑难解答：

![image](https://user-images.githubusercontent.com/33975039/200106325-f039de93-bdef-403f-bcd3-99d376f0b1a2.png)

**Comment by TGSAN** [comment]
一般是网络问题，重新激活试试

**Comment by RinChanNOWWW** [comment]
换成学校给的密钥再用学校的激活器激活成功了。
