### ISSUE TITLE
激活失败，报错0x803F7001

### ISSUE THREAD

**Issue by suzukaze-skrame** [TGSAN/CMWTAT_Digital_Edition#54]
版本：Windows 11 专业版 22H2（实测 Windows 10 也不行）
环境：Unraid 下基于 KVM 的虚拟机
报如下图所示错误：
<img width="836" alt="截屏2022-11-07 16 18 17" src="https://user-images.githubusercontent.com/55702052/200261428-d0cdf566-9a93-4dc0-83a1-bfbbf0622ac2.png">
如果使用 KMS 方式激活则显示激活成功，但是在设置里面显示的是未激活状态。
<img width="839" alt="image" src="https://user-images.githubusercontent.com/55702052/200262074-3b2d0bf7-c6db-4989-aeec-219e71dc4e84.png">

之前用了好多次了，在普通的虚拟机（VMWare之类的）下激活一直都没问题，唯独 KVM 下的虚拟机不行，很奇怪。Windows Update 和 ClipSVC 服务均为开启状态。

**Comment by TGSAN** [comment]
看上去系统安装了KMS密钥，之前是用了其它激活工具吗

**Comment by suzukaze-skrame** [comment]
没有，只用了这个激活工具。因为在数字许可证下获取不到密钥，后来尝试 KMS 依旧无法激活。

**Comment by TGSAN** [comment]
有点奇怪，之后我看看有没有KVM的测试环境来测一下，不知道QEMU能不能复现，这个情况我也是第一次见。

**Comment by TGSAN** [comment]
对了，可以试试疑难解答，看看能不能得到什么新的信息

**Comment by suzukaze-skrame** [comment]
看来没有有用的信息。
<img width="801" alt="image" src="https://user-images.githubusercontent.com/55702052/200305941-94987c92-b683-4a64-af60-13db409fb286.png">

**Comment by suzukaze-skrame** [comment]
啊，测试下来只有 LTSC 版本可以 KMS 激活成功，就先用这个了。

**Comment by Donny3022** [comment]
相同問題，請問這款軟體還可以使用嗎?

**Comment by TGSAN** [comment]
> 相同問題，請問這款軟體還可以使用嗎?

可以的

**Comment by Donny3022** [comment]
那這個問題該怎麼解決?
![image](https://user-images.githubusercontent.com/117832955/201562171-f8fdc3ca-b710-4f22-b22d-b0064e814c74.png)

**Comment by TGSAN** [comment]
> 那這個問題該怎麼解決? ![image](https://user-images.githubusercontent.com/117832955/201562171-f8fdc3ca-b710-4f22-b22d-b0064e814c74.png)

剛剛開了台 Windows 10 的 Azure，試了下沒有問題，目前手上的各種實體設備都沒辦法復現，所以暫時也不知道怎麽解決。
<img width="770" alt="Snipaste_2022-11-14_17-18-25" src="https://user-images.githubusercontent.com/7440847/201623466-01ce4e9e-2d5d-423c-8924-64f389975845.png">

**Comment by suzukaze-skrame** [comment]
找到一个解决方法，虚拟磁盘总线使用 SATA 安装的系统，可以正常激活。默认使用 VirtIO 的情况下则无法激活。
<img width="1463" alt="image" src="https://user-images.githubusercontent.com/55702052/202132658-3e2b0c32-6bbe-4f68-b0f9-4267a2defaa9.png">

**Comment by zhaoxiankai521** [comment]
> 版本：Windows 11 专业版 22H2（实测 Windows 10 也不行） 环境：Unraid 下基于 KVM 的虚拟机 报如下图所示错误： <img alt="截屏2022-11-07 16 18 17" width="836" src="https://user-images.githubusercontent.com/55702052/200261428-d0cdf566-9a93-4dc0-83a1-bfbbf0622ac2.png"> 如果使用 KMS 方式激活则显示激活成功，但是在设置里面显示的是未激活状态。 <img alt="image" width="839" src="https://user-images.githubusercontent.com/55702052/200262074-3b2d0bf7-c6db-4989-aeec-219e71dc4e84.png">
> 
> 之前用了好多次了，在普通的虚拟机（VMWare之类的）下激活一直都没问题，唯独 KVM 下的虚拟机不行，很奇怪。Windows Update 和 ClipSVC 服务均为开启状态。

显示无法卸载旧秘钥怎么搞啊？

**Comment by TGSAN** [comment]
> 找到一个解决方法，虚拟磁盘总线使用 SATA 安装的系统，可以正常激活。默认使用 VirtIO 的情况下则无法激活。 <img alt="image" width="1463" src="https://user-images.githubusercontent.com/55702052/202132658-3e2b0c32-6bbe-4f68-b0f9-4267a2defaa9.png">

VirtIO和Windows一直有兼容问题

**Comment by TGSAN** [comment]
v2.6.4 版本发布了，尝试修复了 VirtIO 的兼容性问题，可以验证一下是否修复。

**Comment by viarotel** [comment]
> VHDX虚拟硬盘中安装的windows 10 22H2 19045.2486 企业版 同样遇到该问题 无法正常激活

采用 v2.6.4版本

**Comment by viarotel** [comment]
> v2.6.4 版本发布了，尝试修复了 VirtIO 的兼容性问题，可以验证一下是否修复。

目前v2.6.4 依然有问题, 换成v2.6.3却成功激活了

**Comment by TGSAN** [comment]
> > v2.6.4 版本发布了，尝试修复了 VirtIO 的兼容性问题，可以验证一下是否修复。
> 
> 目前v2.6.4 依然有问题, 换成v2.6.3却成功激活了

2.6.4在不失败的情况下和2.6.3行为完全一致，所以理论上不存在2.6.3可以新版本不可以的情况。

**Comment by Avimitin** [comment]
在实体机上安装的 Windows 11 依旧能复现这个问题。

**Comment by suzukaze-skrame** [comment]
> v2.6.4 版本发布了，尝试修复了 VirtIO 的兼容性问题，可以验证一下是否修复。

<img width="998" alt="image" src="https://user-images.githubusercontent.com/55702052/218364427-8b12162f-9146-4bb2-a42d-39df1a778041.png">
依旧报错，但是报错代码不同了。

**Comment by TGSAN** [comment]
> 
Error 0x80072EE2: ERROR_INTERNET_TIMEOUT  
这个问题是网络超时，应该是连不上微软的授权服务器，KMS是离线的所以不需要连接微软授权服务器。

**Comment by suzukaze-skrame** [comment]
> > > v2.6.4 版本发布了，尝试修复了 VirtIO 的兼容性问题，可以验证一下是否修复。
> > 
> > 
> > <img alt="image" width="998" src="https://user-images.githubusercontent.com/55702052/218364427-8b12162f-9146-4bb2-a42d-39df1a778041.png">
> > 依旧报错，但是报错代码不同了。
> > 补充：2.6.4 使用 KMS 可以激活成功。
> 
> Error 0x80072EE2: ERROR_INTERNET_TIMEOUT 这个问题是网络超时，应该是连不上微软的授权服务器，KMS是离线的所以不需要连接微软授权服务器。

我又试了一下确实可以了，昨天可能是学校网络有点问题。

**Comment by Avimitin** [comment]
查了一圈没有找到有关的资料，然后用 https://github.com/massgravel/Microsoft-Activation-Scripts 就能正常激活数字许可证了。
