### ISSUE TITLE
M1 parallels Desktop 虚拟机安装arm win11  本软件无法运行

### ISSUE THREAD

**Issue by duleigiser** [TGSAN/CMWTAT_Digital_Edition#55]
**Describe the bug**
双击exe 无反应

**To Reproduce**
mac mini m1 2020 
parallels Desktop
安装arm win11
双击exe 无反应

**Expected behavior**
希望能正常运行 

**Screenshots**

**PC Information (please complete the following information):**
 - CPU Arch: [ARM64]
 - Windows Version: Windows 11 专业版 版本	22H2 操作系统版本	22621.819
 - Original SKU: [Pro]
 - Target SKU: [Pro]
 - Version [2.6.3.0]

**Comment by TGSAN** [comment]
运行没有反应不是程序本身的问题，需要检查系统环境是否正常

**Comment by duleigiser** [comment]
具体要检查什么环境呢 .net 版本还是什么

**Comment by duleigiser** [comment]
重新启动了下虚拟机 成功激活 感谢😀😂
