### ISSUE TITLE
win 11 arm 激活

### ISSUE THREAD

**Issue by serialt** [TGSAN/CMWTAT_Digital_Edition#61]
<img width="724" alt="image" src="https://user-images.githubusercontent.com/58406690/210371424-57f31d18-960d-4f14-b552-2e87415b8f6f.png">

**Comment by TGSAN** [comment]
信息太少，建议按照issue模板填写。一般这个提示是连不上微软激活服务器

**Comment by Lancercmd** [comment]
![QQ截图20230122152307](https://user-images.githubusercontent.com/59906398/213905237-4b7be909-ca46-45ed-8a90-3f09b37e09fe.png)
刚刚在激活新安装的 Win11 22H2 22621.525 x64 时也遇到了同样的问题和错误码，还是使用 `2.5.0.0` 就能正常激活
