### ISSUE TITLE
无法卸载旧秘钥 代码-1

### ISSUE THREAD

**Issue by RiseMrLi** [TGSAN/CMWTAT_Digital_Edition#7]
如题

**Comment by TGSAN** [comment]
再试一次，试试可不可以。有的系统授权损坏（一般出现在Ghost的系统）的确会遇到无法卸载、安装密钥的情况，可以试试管理员权限运行cmd执行`slmgr -upk`命令，如果报错说明系统授权模块是坏掉的或者被精简掉了。
