### ISSUE TITLE
零售版与商业版中的专业版都可以激活吗？

### ISSUE THREAD

**Issue by bai12123** [TGSAN/CMWTAT_Digital_Edition#73]
零售版包含专业版，家庭版；商业版包含专业版，企业版
零售版（consumer editions）与商业版（business editions）中都有专业版，2个都可以激活吗？如果我激活了零售版中的专业版，后续重装系统为企业版，可以用这个升级激活吗？

**Comment by TGSAN** [comment]
可以

**Comment by TGSAN** [comment]
对
