### ISSUE TITLE
这种激活重新安装系统会自动激活吗？

### ISSUE THREAD

**Issue by 392223903** [TGSAN/CMWTAT_Digital_Edition#8]
这种激活重新安装系统会自动激活吗？

**Comment by lonetmoon** [comment]
和微软账户绑定了就行。

**Comment by TGSAN** [comment]
会的，不一定要和微软帐号绑定，绑定之后是可以在硬件更换后用来迁移授权的，如果只是单纯的重装系统是可以直接自动激活（不需要账号绑定）

**Comment by 392223903** [comment]
> 会的，不一定要和微软帐号绑定，绑定之后是可以在硬件更换后用来迁移授权的，如果只是单纯的重装系统是可以直接自动激活（不需要账号绑定）

万分感谢
