### ISSUE TITLE
Win10/11激活新方法出炉，依旧永久

### ISSUE THREAD

**Issue by Firedoge1** [TGSAN/CMWTAT_Digital_Edition#81]
微软在2015年推出了Windows10系统，并承诺在一年内为win7和win8.1提供Windows10的免费升级，但一年过去之后，甚至8年后，依然可以免费升级，有人利用这个“后门"开发了激活工具，使得win10、win11可以永久激活。但是，微软近日发布了一则消息，宣布关闭免费升级通道。同时微软服务器也开始阻止激活工具请求。

不过，[massgrave.dev](http://massgrave.dev/)团队又研究出一种新的激活方法，经过本人测试（虚拟机里的Windows11专业工作站班），这个新方法确实有效，可以直接激活数字许可证，只需要下载这个脚本，双击之后，按数字1即可激活Windows。

同时，这个脚本也可以激活Office。按数字2即可。

脚本下载：

[MAS_AIO.cmd官方版下载丨最新版下载丨绿色版下载丨APP下载-123云盘](https://www.123pan.com/s/AuyjVv-p6v0v.html)

**Comment by sunxiaoshun** [comment]
6

**Comment by aadorable** [comment]
6，pd win 11专业版激活了

**Comment by Jialiangfan** [comment]
6666

**Comment by hongliang666** [comment]
太牛了
