### ISSUE TITLE
下载后自动被删删除

### ISSUE THREAD

**Issue by weihuajiang** [TGSAN/CMWTAT_Digital_Edition#9]
下载解压缩后，会被自动删除，怎么回事？还有你源码使用了很多其他类库，比如newtonSoft.json,MaterialDesignThemes，为什么exe文件没有这些dll文件？exe文件和build后文件肯定不同，隐藏了什么动？

**Comment by TGSAN** [comment]
自动删除请检查杀毒软件，没数字签名的软件基本上发布一段时间国产杀软都会报毒。另外库是通过反射动态载入的。
