### ISSUE TITLE
家庭版windows升级失败错误代码 0x800704ec

### ISSUE THREAD

**Issue by zhaoliang0302** [TGSAN/CMWTAT_Digital_Edition#94]
2.7最新版，win11 23h2家庭版，点升级完整版windows显示“windows升级失败错误代码 0x800704ec”。clash开了或者不开都是这样报错

**Comment by TGSAN** [comment]
![Screenshot_20240825-011745](https://github.com/user-attachments/assets/407c4e71-c4eb-4380-8868-2bbd3e559259)
设备管理员不允许升级，可能是配置了组策略，或者OEM厂商禁止的

**Comment by zhaoliang0302** [comment]
确实是电脑到手用了优化软件禁用了一些功能，可能这个原因引起的，现在排查就很难了

**Comment by TGSAN** [comment]
通过三方软件”优化“破坏系统后只能通过第三方软件自己去还原，除了软件自己以外别人都不知道它会干些什么。
